import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { downloadBlob } from '@/shared/utils/download';
import type { AttendanceRecord } from '../types/export.types';
import { formatDate, formatDisplayDate, buildGeneralReport } from './helpers';

// ── Shared: load logo as base64 ──────────────────────────────────────────────
function loadLogo(): Promise<{ base64: string; w: number; h: number } | null> {
  return new Promise((resolve) => {
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.src = '/logo.png';
    img.onload = () => {
      const c = document.createElement('canvas');
      c.width = img.naturalWidth;
      c.height = img.naturalHeight;
      c.getContext('2d')?.drawImage(img, 0, 0);
      resolve({ base64: c.toDataURL('image/png'), w: img.naturalWidth, h: img.naturalHeight });
    };
    img.onerror = () => resolve(null);
  });
}

function getGeneratedBy(): string {
  const stored = localStorage.getItem('user');
  const parsed = stored ? JSON.parse(stored) : null;
  return parsed?.name || parsed?.email || parsed?.username || 'Ada Barbershop System';
}

function timestamp(): string {
  return new Date().toLocaleString('id-ID', {
    day: '2-digit', month: 'long', year: 'numeric',
    hour: '2-digit', minute: '2-digit', second: '2-digit', hour12: false,
  });
}

// ── Detail PDF ───────────────────────────────────────────────────────────────
export async function generateDetailPDF(
  data: AttendanceRecord[], startDate: Date, endDate: Date, recordCount: number,
) {
  const logo = await loadLogo();
  const generatedBy = getGeneratedBy();
  const generatedAt = timestamp();
  const doc = new jsPDF({ orientation: 'landscape' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const drawHF = (pn: number) => {
    doc.setFillColor(255, 255, 255); doc.rect(0, 0, pageW, 20, 'F');
    if (logo) {
      const lh = 14; const lw = (logo.w / logo.h) * lh;
      doc.addImage(logo.base64, 'PNG', 10, 3, lw, lh);
      doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(30, 58, 138);
      doc.text('Rekapan Absensi — Ada Barbershop', 10 + lw + 6, 12);
    } else {
      doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(30, 58, 138);
      doc.text('Rekapan Absensi — Ada Barbershop', 10, 12);
    }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(100, 100, 100);
    doc.text(`Dibuat: ${generatedAt}`, pageW - 10, 12, { align: 'right' });
    doc.setDrawColor(200, 200, 200); doc.setLineWidth(0.3);
    doc.line(10, pageH - 12, pageW - 10, pageH - 12);
    doc.setFont('helvetica', 'italic'); doc.setFontSize(7.5); doc.setTextColor(120, 120, 120);
    doc.text(`Generated at: ${generatedAt}`, 10, pageH - 6);
    doc.setFont('helvetica', 'normal');
    doc.text(`Halaman ${pn}`, pageW / 2, pageH - 6, { align: 'center' });
    doc.setFont('helvetica', 'italic');
    doc.text(`Generated by: ${generatedBy}`, pageW - 10, pageH - 6, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  };

  autoTable(doc, {
    startY: 26, margin: { top: 26, bottom: 18 },
    head: [['No', 'Nama', 'Email', 'Role', 'Cabang', 'Tanggal', 'Check In', 'Check Out', 'Status In', 'Status Out']],
    body: data.map((r, i) => [i + 1, r.employeeName, r.employeeEmail, r.employeeRole, r.branchName, r.date, r.checkInTime, r.checkOutTime, r.checkInStatus, r.checkOutStatus]),
    styles: { fontSize: 8, cellPadding: 3 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [243, 244, 246] },
    didDrawPage: (d) => {
      drawHF(d.pageNumber);
      if (d.pageNumber === 1) {
        doc.setFontSize(9); doc.setTextColor(80, 80, 80);
        doc.text(`Periode: ${formatDisplayDate(startDate)} s.d. ${formatDisplayDate(endDate)}   |   Total: ${recordCount} data`, 10, 23);
        doc.setTextColor(0, 0, 0);
      }
    },
  });

  downloadBlob(doc.output('blob'), `rekapan-absensi_${formatDate(startDate)}_sd_${formatDate(endDate)}.pdf`);
}

// ── Detail Excel ─────────────────────────────────────────────────────────────
export function generateDetailExcel(data: AttendanceRecord[], startDate: Date, endDate: Date) {
  const rows = data.map((r, i) => ({
    No: i + 1, 'ID Absensi': r.attendanceId, 'Nama Karyawan': r.employeeName,
    Email: r.employeeEmail, Role: r.employeeRole, Cabang: r.branchName,
    Tanggal: r.date, 'Check In': r.checkInTime, 'Check Out': r.checkOutTime,
    'Status Check In': r.checkInStatus, 'Status Check Out': r.checkOutStatus,
  }));
  const ws = XLSX.utils.json_to_sheet(rows);
  ws['!cols'] = Object.keys(rows[0] || {}).map((k) => ({ wch: Math.max(k.length, 16) }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Rekapan Absensi');
  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  downloadBlob(
    new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    `rekapan-absensi_${formatDate(startDate)}_sd_${formatDate(endDate)}.xlsx`,
  );
}

// ── General PDF ──────────────────────────────────────────────────────────────
export async function generateGeneralPDF(data: AttendanceRecord[], startDate: Date, endDate: Date) {
  const rows = buildGeneralReport(data);
  const logo = await loadLogo();
  const generatedBy = getGeneratedBy();
  const generatedAt = timestamp();
  const doc = new jsPDF({ orientation: 'portrait' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const drawHF = (pn: number) => {
    doc.setFillColor(255, 255, 255); doc.rect(0, 0, pageW, 20, 'F');
    if (logo) {
      const lh = 14; const lw = (logo.w / logo.h) * lh;
      doc.addImage(logo.base64, 'PNG', 10, 3, lw, lh);
      doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(30, 58, 138);
      doc.text('Laporan General — Ada Barbershop', 10 + lw + 6, 12);
    } else {
      doc.setFont('helvetica', 'bold'); doc.setFontSize(12); doc.setTextColor(30, 58, 138);
      doc.text('Laporan General — Ada Barbershop', 10, 12);
    }
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(100, 100, 100);
    doc.text(`Dibuat: ${generatedAt}`, pageW - 10, 12, { align: 'right' });
    doc.setDrawColor(200, 200, 200); doc.setLineWidth(0.3);
    doc.line(10, pageH - 12, pageW - 10, pageH - 12);
    doc.setFont('helvetica', 'italic'); doc.setFontSize(7.5); doc.setTextColor(120, 120, 120);
    doc.text(`Generated at: ${generatedAt}`, 10, pageH - 6);
    doc.setFont('helvetica', 'normal');
    doc.text(`Halaman ${pn}`, pageW / 2, pageH - 6, { align: 'center' });
    doc.setFont('helvetica', 'italic');
    doc.text(`Generated by: ${generatedBy}`, pageW - 10, pageH - 6, { align: 'right' });
    doc.setTextColor(0, 0, 0);
  };

  autoTable(doc, {
    startY: 26, margin: { top: 26, bottom: 18 },
    head: [['No', 'Cabang Barbershop', 'Status IN (On Time)', 'Status OUT (On Time)']],
    body: rows.map((r, i) => [i + 1, r.barbershopName, r.onTimeIn, r.onTimeOut]),
    styles: { fontSize: 9, cellPadding: 4 },
    headStyles: { fillColor: [30, 58, 138], textColor: 255, fontStyle: 'bold' },
    alternateRowStyles: { fillColor: [243, 244, 246] },
    columnStyles: { 0: { halign: 'center', cellWidth: 12 }, 2: { halign: 'center' }, 3: { halign: 'center' } },
    didDrawPage: (d) => {
      drawHF(d.pageNumber);
      if (d.pageNumber === 1) {
        doc.setFontSize(9); doc.setTextColor(80, 80, 80);
        doc.text(`Periode: ${formatDisplayDate(startDate)} s.d. ${formatDisplayDate(endDate)}   |   ${rows.length} cabang`, 10, 23);
        doc.setTextColor(0, 0, 0);
      }
    },
  });

  downloadBlob(doc.output('blob'), `laporan-general_${formatDate(startDate)}_sd_${formatDate(endDate)}.pdf`);
}

// ── General Excel ────────────────────────────────────────────────────────────
export function generateGeneralExcel(data: AttendanceRecord[], startDate: Date, endDate: Date) {
  const rows = buildGeneralReport(data).map((r, i) => ({
    No: i + 1, 'Cabang Barbershop': r.barbershopName,
    'Jumlah Status IN (On Time)': r.onTimeIn, 'Jumlah Status OUT (On Time)': r.onTimeOut,
  }));
  const ws = XLSX.utils.json_to_sheet(rows);
  ws['!cols'] = Object.keys(rows[0] || {}).map((k) => ({ wch: Math.max(k.length + 2, 18) }));
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Laporan General');
  const out = XLSX.write(wb, { bookType: 'xlsx', type: 'array' });
  downloadBlob(
    new Blob([out], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' }),
    `laporan-general_${formatDate(startDate)}_sd_${formatDate(endDate)}.xlsx`,
  );
}
